---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Prima di distribuire gli ONTAP tools for VMware vSphere, è necessario conoscere i requisiti di spazio per il pacchetto di distribuzione e alcuni requisiti di base del sistema host. 
---
= ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di distribuire gli ONTAP tools for VMware vSphere, è necessario conoscere i requisiti di spazio per il pacchetto di distribuzione e alcuni requisiti di base del sistema host.

È possibile utilizzare gli ONTAP tools for VMware vSphere con VMware vCenter Server Virtual Appliance (vCSA).  È necessario distribuire gli ONTAP tools for VMware vSphere su un client vSphere supportato che includa il sistema ESXi.



== Requisiti di sistema

* *Requisiti di spazio del pacchetto di installazione per nodo*
+
** 15 GB per installazioni thin provisioning
** 348 GB per installazioni con provisioning spesso


* *Requisiti di dimensionamento del sistema host* La memoria consigliata in base alle dimensioni della distribuzione è quella indicata nella tabella seguente.  Per implementare l'alta disponibilità (HA), sarà necessaria una dimensione dell'appliance pari a tre volte quella specificata nella tabella.


|===


| *Tipo di distribuzione* | *CPU per nodo* | *Memoria (GB) per nodo* | *Spazio su disco (GB) fornito per nodo* 


| Piccolo | 9 | 18 | 350 


| Medio | 13 | 26 | 350 


| NOTA: la distribuzione di grandi dimensioni è solo per la configurazione HA. | 17 | 34 | 350 
|===

NOTE: Quando il backup è abilitato, ogni cluster di strumenti ONTAP necessita di altri 50 GB di spazio sul datastore in cui sono distribuite le VM.  Pertanto, la modalità non HA richiede 400 GB, mentre la modalità HA richiede 1100 GB di spazio in totale.



== Requisiti minimi di archiviazione e applicazione

|===
| Archiviazione, host e applicazioni | Requisiti di versione 


| ONTAP | 9.14.1, 9.15.1, 9.16.0, 9.16.1 e 9.16.1P3 FAS, ASA serie A, ASA serie C, AFF serie A, AFF serie C e ASA r2. 


| Gli strumenti ONTAP supportano gli host ESXi | 7.0.3 in poi 


| Strumenti ONTAP supportati da vCenter Server | 7.0U3 in poi 


| Fornitore VASA | 3,0 


| Applicazione OVA | 10,4 


| Host ESXi per distribuire la macchina virtuale degli strumenti ONTAP | 7.0U3 e 8.0U3 


| vCenter Server per distribuire la macchina virtuale degli strumenti ONTAP | 7.0 e 8.0 
|===

NOTE: A partire dagli ONTAP tools for VMware vSphere 10.4, l'hardware della macchina virtuale è stato modificato dalla versione 10 alla 17.

Lo strumento Interoperability Matrix Tool (IMT) contiene le informazioni più recenti sulle versioni supportate di ONTAP, vCenter Server, host ESXi e applicazioni plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Strumento di matrice di interoperabilità"^]



== Requisiti portuali

La tabella seguente illustra le porte di rete utilizzate da NetApp e le relative funzioni. Esistono tre diversi tipi di porte:

* Porte esterne: queste porte sono accessibili dall'esterno del cluster o del nodo Kubernetes.  Consentono ai servizi di comunicare con reti o utenti esterni, consentendo l'integrazione con sistemi esterni all'ambiente cluster.
* Porte inter-nodo: queste porte consentono la comunicazione tra i nodi all'interno del cluster Kubernetes.  Sono necessari per attività di clustering come la condivisione di dati e la collaborazione.  Per le distribuzioni a nodo singolo, le porte tra nodi vengono utilizzate solo all'interno del nodo e non necessitano di accesso esterno.  Le porte internodo possono accettare traffico dall'esterno del cluster.  Bloccare l'accesso a Internet alle porte tra nodi tramite regole firewall.
* Porte interne: queste porte comunicano all'interno del cluster Kubernetes utilizzando indirizzi ClusterIP.  Non sono esposti esternamente e non devono essere aggiunti alle regole del firewall.



NOTE: Assicurarsi che tutti i nodi degli strumenti ONTAP risiedano nella stessa subnet per mantenere una comunicazione ininterrotta tra loro.


|===
| *Nome del servizio/componente* | *Porta* | *Protocollo* | *Tipo di porta* | *Descrizione* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Esterno | Porta di passaggio per le comunicazioni in entrata per il servizio VASA Provider. Il certificato autofirmato del provider VASA e il certificato CA personalizzato sono ospitati su questa porta. 


| SSH | 22 | TCP | Esterno | Secure Shell per l'accesso remoto al server e l'esecuzione dei comandi. 


| server rke2 | 9345 | TCP | Inter-nodo | API del supervisore RKE2 (limita alle reti attendibili). 


| kube-apiserver | 6443 | TCP | Inter-nodo | Porta del server API Kubernetes (limita alle reti attendibili). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nodo | Utilizzato per la comunicazione RPC tra servizi. 


| coredns (DNS) | 53 | TCP/UDP | Inter-nodo | Servizio Domain Name System (DNS) per la risoluzione dei nomi all'interno del cluster. 


| NTP | 123 | UDP | Inter-nodo | Network Time Protocol (NTP) per la sincronizzazione dell'ora. 


| ecc. | 2379, 2380, 2381 | TCP | Inter-nodo | Archivio chiave-valore per i dati del cluster. 


| kube-vip | 2112 | TCP | Inter-nodo | Porta del server API Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nodo | Componente Kubernetes 


| kube-controller | 10257 | TCP | Inter-nodo | Componente Kubernetes 


| cloud controller | 10258 | TCP | Inter-nodo | Componente Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nodo | Componente Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nodo | Componente Kubernetes 


| nodo calico | 9091, 9099 | TCP | Inter-nodo | Componente di rete Calico. 


| contenitore | 10010 | TCP | Inter-nodo | Servizio demone del contenitore. 


| VXLAN (flanella) | 8472 | UDP | Inter-nodo | Rete di sovrapposizione per la comunicazione tra pod. 
|===

NOTE: Per le distribuzioni HA, assicurarsi che la porta UDP 8472 sia aperta tra tutti i nodi.  Questa porta consente la comunicazione pod-to-pod tra i nodi; bloccandola si interromperà la rete tra nodi.



== Limiti di configurazione per distribuire gli ONTAP tools for VMware vSphere

È possibile utilizzare la seguente tabella come guida per configurare gli ONTAP tools for VMware vSphere.

|===


| *Dispiegamento* | *Tipo* | *Numero di vVols* | *Numero di host* 


| Non-HA | Piccola (S) | ~12K | 32 


| Non-HA | Medio (M) | ~24K | 64 


| Alta disponibilità | Piccola (S) | ~24K | 64 


| Alta disponibilità | Medio (M) | ~50k | 128 


| Alta disponibilità | Grande (L) | ~100k | 256 [NOTA] Il numero di host nella tabella mostra il numero totale di host da più vCenter. 
|===


== ONTAP tools for VMware vSphere - Storage Replication Adapter (SRA)

La tabella seguente mostra i numeri supportati per istanza di VMware Live Site Recovery utilizzando gli ONTAP tools for VMware vSphere.

|===
| *Dimensioni di distribuzione vCenter* | *Piccolo* | *Medio* 


| Numero totale di macchine virtuali configurate per la protezione mediante replica basata su array | 2000 | 5000 


| Numero totale di gruppi di protezione della replica basati su array | 250 | 250 


| Numero totale di gruppi di protezione per piano di ripristino | 50 | 50 


| Numero di datastore replicati | 255 | 255 


| Numero di VM | 4000 | 7000 
|===
Nella tabella seguente viene mostrato il numero di VMware Live Site Recovery e i corrispondenti ONTAP tools for VMware vSphere .

|===


| *Numero di istanze di VMware Live Site Recovery* | * Dimensioni di distribuzione degli strumenti ONTAP * 


| Fino a 4 | Piccolo 


| da 4 a 8 | Medio 


| Più di 8 | Grande 
|===
Per ulteriori informazioni, consulta  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limiti operativi di VMware Live Site Recovery"] .
