---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Per consentire a VMware Live Site Recovery di comunicare con SRA, è necessario aggiornare le credenziali SRA sul server VMware Live Site Recovery se sono state modificate. 
---
= Aggiorna le credenziali SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per consentire a VMware Live Site Recovery di comunicare con SRA, è necessario aggiornare le credenziali SRA sul server VMware Live Site Recovery se sono state modificate.

.Prima di iniziare
Avresti dovuto eseguire i passaggi menzionati nell'argomentolink:../protect/configure-on-srm-appliance.html["Configurazione di SRA sull'appliance VMware Live Site Recovery"] .

.Passi
. Eseguire i seguenti comandi per eliminare la cartella della macchina VMware Live Site Recovery memorizzata nella cache degli strumenti ONTAP , nome utente e password:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Eseguire il comando Perl per configurare SRA con le nuove credenziali:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>`È necessario racchiudere il valore della password tra virgolette singole.
+
Viene visualizzato un messaggio di conferma che le credenziali di archiviazione sono state archiviate.  SRA può comunicare con il server SRA utilizzando l'indirizzo IP, la porta e le credenziali forniti.




