---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP tools for VMware vSphere è una raccolta di strumenti per la gestione del ciclo di vita delle macchine virtuali.  Si integra con l"ecosistema VMware e aiuta nel provisioning, nella protezione di base e nel disaster recovery delle macchine virtuali.' 
---
= Panoramica ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere è un set di strumenti per la gestione del ciclo di vita delle macchine virtuali. Si integra con l'ecosistema VMware per facilitare il provisioning del datastore e fornire una protezione di base per le macchine virtuali.  Gli ONTAP tools for VMware vSphere sono una raccolta di microservizi scalabili orizzontalmente e basati su eventi, distribuiti come Open Virtual Appliance (OVA).  Questa versione integra l'API REST con ONTAP.

Gli ONTAP tools for VMware vSphere sono costituiti da quanto segue:

* Funzionalità della macchina virtuale come protezione di base e ripristino di emergenza
* Fornitore VASA per la gestione granulare delle VM
* Gestione basata su policy di archiviazione
* Adattatore di replicazione dello storage (SRA)

