---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: 'Sebbene REST stabilisca un insieme comune di tecnologie e best practice, l"implementazione esatta di ciascuna API può variare in base alle scelte di progettazione.  Prima di utilizzare gli ONTAP tools for VMware vSphere 10 REST API, è necessario avere familiarità con la progettazione.' 
---
= Dettagli di implementazione per gli ONTAP tools for VMware vSphere 10 REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sebbene REST stabilisca un insieme comune di tecnologie e best practice, l'implementazione esatta di ciascuna API può variare in base alle scelte di progettazione.  Prima di utilizzare gli ONTAP tools for VMware vSphere 10 REST API, è necessario avere familiarità con la progettazione.

L'API REST include diverse categorie di risorse, come vCenter e Aggregati.  Rivedere illink:../automation/api-reference.html["Riferimento API"] per maggiori informazioni.



== Come accedere alla REST API

È possibile accedere agli ONTAP tools for VMware vSphere 10 REST API tramite l'indirizzo IP degli strumenti ONTAP insieme alla porta.  L'URL completo è composto da diverse parti, tra cui:

* Indirizzo IP e porta degli strumenti ONTAP
* Versione API
* Categoria di risorse
* Risorsa specifica


È necessario configurare l'indirizzo IP durante la configurazione iniziale, mentre la porta rimane fissa a 8443. La prima parte dell'URL è coerente per ogni istanza ONTAP tools for VMware vSphere 10; cambiano solo la categoria della risorsa e la risorsa specifica tra gli endpoint.


CAUTION: I valori dell'indirizzo IP e della porta negli esempi seguenti sono solo a scopo illustrativo.  È necessario modificare questi valori per il proprio ambiente.

.Esempio per accedere ai servizi di autenticazione
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

Questo URL può essere utilizzato per richiedere un token di accesso tramite il metodo POST.

.Esempio per elencare i server vCenter
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

Questo URL può essere utilizzato per richiedere un elenco delle istanze del server vCenter definite utilizzando il metodo GET.



== Dettagli HTTP

Gli ONTAP tools for VMware vSphere 10 REST API utilizzano HTTP e parametri correlati per agire sulle istanze e sulle raccolte di risorse.  Di seguito vengono presentati i dettagli dell'implementazione HTTP.



=== Metodi HTTP

I metodi o verbi HTTP supportati dall'API REST sono presentati nella tabella seguente.

[cols="15,15,70"]
|===
| Metodo | CRUD | Descrizione 


| OTTENERE | Leggere | Recupera le proprietà dell'oggetto per un'istanza o una raccolta di risorse.  Questa operazione è considerata un'operazione di elenco quando utilizzata con una raccolta. 


| INVIARE | Creare | Crea una nuova istanza di risorsa in base ai parametri di input. 


| METTERE | Aggiornamento | Aggiorna un'intera istanza di risorsa con il corpo della richiesta JSON fornito. I valori chiave non modificabili dall'utente vengono mantenuti. 


| TOPPA | Aggiornamento | Richiede che un insieme di modifiche selezionate nella richiesta vengano applicate all'istanza della risorsa. 


| ELIMINARE | Eliminare | Elimina un'istanza di risorsa esistente. 
|===


=== Intestazioni di richiesta e risposta

La tabella seguente riassume le intestazioni HTTP più importanti utilizzate con l'API REST.

[cols="30,15,55"]
|===
| Intestazione | Tipo | Note sull'utilizzo 


| Accettare | Richiesta | Questo è il tipo di contenuto che l'applicazione client può accettare.  I valori validi includono '\*/*` o `application/json` . 


| x-auth | Richiesta | Contiene un token di accesso che identifica l'utente che invia la richiesta tramite l'applicazione client. 


| Tipo di contenuto | Risposta | Restituito dal server in base al `Accept` intestazione della richiesta. 
|===


=== Codici di stato HTTP

Di seguito sono descritti i codici di stato HTTP utilizzati dall'API REST.

[cols="15,20,65"]
|===
| Codice | Senso | Descrizione 


| 200 | OK | Indica il successo delle chiamate che non creano una nuova istanza di risorsa. 


| 201 | Creato | È stato creato correttamente un oggetto con un identificatore univoco per l'istanza della risorsa. 


| 202 | Accettato | La richiesta è stata accettata ed è stato creato un processo in background per eseguirla. 


| 204 | Nessun contenuto | La richiesta è stata accettata, anche se non è stato restituito alcun contenuto. 


| 400 | Brutta richiesta | L'input della richiesta non è riconosciuto o è inappropriato. 


| 401 | Non autorizzato | L'utente non è autorizzato e deve autenticarsi. 


| 403 | Vietato | L'accesso è negato a causa di un errore di autorizzazione. 


| 404 | Non trovato | La risorsa a cui si fa riferimento nella richiesta non esiste. 


| 409 | Conflitto | Il tentativo di creare un oggetto non è riuscito perché l'oggetto esiste già. 


| 500 | Errore interno | Si è verificato un errore interno generale sul server. 
|===


== Autenticazione

L'autenticazione di un client all'API REST viene eseguita tramite un token di accesso.  Le caratteristiche rilevanti del token e del processo di autenticazione includono:

* Il client deve richiedere un token utilizzando le credenziali di amministratore di ONTAP Tools Manager (nome utente e password).
* I token sono formattati come JSON Web Token (JWT).
* Ogni token scade dopo 60 minuti.
* Le richieste API da un client devono includere il token nel `x-auth` intestazione della richiesta.


Fare riferimento alink:../automation/first-call.html["La tua prima chiamata API REST"] per un esempio di richiesta e utilizzo di un token di accesso.



== Richieste sincrone e asincrone

La maggior parte delle chiamate API REST vengono completate rapidamente e pertanto vengono eseguite in modo sincrono.  Ciò significa che restituiscono un codice di stato (ad esempio 200) dopo che una richiesta è stata completata.  Le richieste che richiedono più tempo per essere completate vengono eseguite in modo asincrono tramite un processo in background.

Dopo aver emesso una chiamata API eseguita in modo asincrono, il server restituisce un codice di stato HTTP 202.  Indica che la richiesta è stata accettata ma non ancora completata.  È possibile interrogare il processo in background per determinarne lo stato, incluso se è riuscito o meno.

L'elaborazione asincrona viene utilizzata per diversi tipi di operazioni di lunga durata, tra cui le operazioni datastore e vVol.  Per ulteriori informazioni, fare riferimento alla categoria Job Manager dell'API REST nella pagina Swagger.
