---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, ontap tools for VMware vSphere 
summary: Fornisce informazioni importanti su questa versione degli ONTAP tools for VMware vSphere, tra cui nuove funzionalità e miglioramenti, problemi risolti, problemi noti, avvertenze e limitazioni. 
---
= Note di rilascio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove e migliorate funzionalità disponibili negli ONTAP tools for VMware vSphere 10.4.

Per un elenco completo delle nuove funzionalità e dei miglioramenti, fare riferimentoxref:whats-new.adoc[Novità negli ONTAP tools for VMware vSphere 10.4] .

Per saperne di più sulla scelta giusta per la tua distribuzione di migrare dagli ONTAP tools for VMware vSphere 9 agli strumenti ONTAP 10.4, fai riferimento axref:ontap-tools-9-ontap-tools-10-feature-comparison.adoc[Confronto delle funzionalità ONTAP tools for VMware vSphere 9 e ONTAP tools for VMware vSphere 10] .  È supportata la migrazione dagli ONTAP tools for VMware vSphere 9.12-D e 9.13-D agli ONTAP tools for VMware vSphere 10.4.

Per maggiori informazioni, fare riferimento al https://library.netapp.com/ecm/ecm_download_file/ECMLP3343864["Note sulla versione ONTAP tools for VMware vSphere 10.4"^] . Per accedere alle Note sulla versione è necessario effettuare l'accesso con il proprio account NetApp o creare un account.
