---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords:  
summary: Aggiungere nuovi host VMware vSphere agli ONTAP tools for VMware vSphere. 
---
= Aggiungi nuovi host VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggiungere nuovi host VMware vSphere agli ONTAP tools for VMware vSphere per gestire e proteggere i datastore sugli host.

.Passi
. Aggiungi un host al tuo cluster VMware vSphere seguendo il flusso di lavoro a pagina: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/use-quickstart-to-add---host-to-a-cluster.html["Come aggiungere un host ESX al cluster vSphere utilizzando il flusso di lavoro di avvio rapido"]
. Dopo aver aggiunto l'host, vai al menu principale degli strumenti ONTAP e seleziona *Scopri* nel pannello di panoramica.  Attendi il completamento del processo di scoperta.  In alternativa, è possibile attendere il completamento della rilevazione dell'host pianificata.


.Risultato
Il nuovo host è ora rilevato e gestito dagli ONTAP tools for VMware vSphere.  È possibile procedere alla gestione del datastore sul nuovo host.

.Argomenti correlati
* link:../manage/mount-a-vvols-datastore.html["Montare un datastore vVols"]sui nuovi host.
* link:../manage/mount-datastores-on-host.html["Montare il datastore NFS e VMFS"]sui nuovi host.

