---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Una singola istanza degli ONTAP tools for VMware vSphere può gestire più istanze di vCenter Server.  Gli ONTAP tools for VMware vSphere vengono distribuiti con un certificato autofirmato per VASA Provider.  In questo modo è possibile gestire una sola istanza di vCenter Server per i datastore vVols . 
---
= Gestisci i certificati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, durante la distribuzione viene generato un certificato autofirmato per gli strumenti ONTAP e VASA Provider.  Utilizzando l'interfaccia di ONTAP Tools Manager, è possibile rinnovare il certificato o aggiornarlo a una CA personalizzata.  I certificati CA personalizzati sono obbligatori in una distribuzione multi-vCenter.

.Prima di iniziare
* Il nome di dominio su cui viene emesso il certificato deve essere mappato all'indirizzo IP virtuale.
* Eseguire il controllo nslookup sul nome di dominio per verificare se il dominio viene risolto nell'indirizzo IP previsto.
* I certificati devono essere creati con il nome di dominio e l'indirizzo IP degli strumenti ONTAP .



NOTE: Un indirizzo IP degli strumenti ONTAP deve corrispondere a un nome di dominio completamente qualificato (FQDN).  I certificati devono contenere lo stesso FQDN mappato all'indirizzo IP degli strumenti ONTAP nei nomi oggetto o nei nomi alternativi dell'oggetto.


NOTE: Non è possibile passare da un certificato firmato da una CA a un certificato autofirmato.

[role="tabbed-block"]
====
.Aggiorna il certificato degli strumenti ONTAP
--
La scheda Strumenti ONTAP mostra dettagli come il tipo di certificato (autofirmato/firmato da CA) e il nome di dominio.  Durante la distribuzione, per impostazione predefinita viene generato un certificato autofirmato.  È possibile rinnovare il certificato o aggiornarlo a CA.

.Passi
. Avviare ONTAP Tools Manager da un browser web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Accedi con le credenziali di amministratore ONTAP tools for VMware vSphere fornite durante la distribuzione.
. Selezionare *Certificati* > *Strumenti ONTAP * > *Rinnova* per rinnovare i certificati.
+
È possibile rinnovare il certificato se è scaduto o se sta per scadere.  L'opzione di rinnovo è disponibile quando il tipo di certificato è firmato da una CA.  Nella finestra pop-up, fornire i dettagli del certificato del server, della chiave privata, della CA radice e del certificato intermedio.

+

NOTE: Il sistema sarà offline finché il certificato non verrà rinnovato e verrai disconnesso dall'interfaccia di ONTAP Tools Manager.

. Per aggiornare il certificato autofirmato a un certificato CA personalizzato, selezionare l'opzione *Certificati* > *Strumenti ONTAP * > *Aggiorna a CA*.
+
.. Nella finestra pop-up, carica il certificato del server, la chiave privata del certificato del server, il certificato CA radice e i file del certificato intermedio.
.. Inserisci il nome di dominio per il quale hai generato questo certificato e aggiorna il certificato.
+

NOTE: Il sistema sarà offline fino al completamento dell'aggiornamento e l'utente verrà disconnesso dall'interfaccia di ONTAP Tools Manager.





--
.Aggiorna il certificato del fornitore VASA
--
Gli ONTAP tools for VMware vSphere vengono distribuiti con un certificato autofirmato per VASA Provider.  In questo modo è possibile gestire una sola istanza di vCenter Server per i datastore vVols .  Quando si gestiscono più istanze di vCenter Server e si desidera abilitare la funzionalità vVols su di esse, è necessario modificare il certificato autofirmato in un certificato CA personalizzato.

.Passi
. Avviare ONTAP Tools Manager da un browser web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Accedi con le credenziali di amministratore ONTAP tools for VMware vSphere fornite durante la distribuzione.
. Selezionare *Certificati* > *Fornitore VASA* o *Strumenti ONTAP * > *Rinnova* per rinnovare i certificati.
. Selezionare *Certificati* > *Provider VASA* o *Strumenti ONTAP * > *Aggiorna a CA* per aggiornare il certificato autofirmato in un certificato CA personalizzato.
+
.. Nella finestra pop-up, carica il certificato del server, la chiave privata del certificato del server, il certificato CA radice e i file del certificato intermedio.
.. Inserisci il nome di dominio per il quale hai generato questo certificato e aggiorna il certificato.
+

NOTE: Il sistema sarà offline fino al completamento dell'aggiornamento e l'utente verrà disconnesso dall'interfaccia di ONTAP Tools Manager.





--
====