---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Se hai dimenticato la password di ONTAP Tools Manager, puoi reimpostare le credenziali di amministratore utilizzando il token generato dalla console di manutenzione di ONTAP tools for VMware vSphere . 
---
= Reimposta la password del gestore degli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se hai dimenticato la password di ONTAP Tools Manager, puoi reimpostare le credenziali di amministratore utilizzando il token generato dalla console di manutenzione di ONTAP tools for VMware vSphere .

.Passi
. Avviare ONTAP Tools Manager da un browser web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Nella schermata di accesso, seleziona l'opzione *Reimposta password*.
+
Per reimpostare la password del Manager, è necessario generare il token di reimpostazione utilizzando gli ONTAP tools for VMware vSphere .

+
.. Dal vCenter Server, aprire la console di manutenzione
.. Immettere '2' per selezionare l'opzione Configurazione di sistema
.. Inserisci '3' per modificare la password utente 'maint'.


. Nella finestra pop-up per la modifica della password, inserisci il token di reimpostazione della password, il nome utente e i dettagli della nuova password.
. Selezionare *Reimposta* per implementare le modifiche.  Una volta reimpostata la password, potrai utilizzare la nuova password per accedere.

